name: Publish to TestPyPi
on:
  release:
    types:
      - published
jobs:
    publish-pypi:
      name: Publish distribution ${{ github.ref }}
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      environment: release
      steps:
        - uses: actions/checkout@v4
        - name: Setup PDM
          uses: pdm-project/setup-pdm@v4
        - name: upload to testpypi
          run: pdm publish --repository testpypi
    publish-docs:
      name: Create documentation for ${{ github.ref }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup PDM
          uses: pdm-project/setup-pdm@v4
        - name: Install docs dependencies
          run: pdm sync -G docs
        - name: Setup git
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
        - name: Publish docs ${{ github.ref }}
          run: |
            eval $(pdm venv activate)
            mike deploy --push --update-aliases v$(versioningit) latest