name: Verify Pull Request
run-name: Verify Pull Request (${{ github.actor }})
on: [pull_request]
jobs: 
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install
      - name: Check source formatting
        run: |
          pwd
          ls -la
          pdm run check-source-formatting
      - name: Check tests formatting
        run: pdm run check-test-formatting
      - name: Run tests
        run: pdm run tests
        
        